plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

base {
    archivesName = mod_id + "-" + mod_version + "-" + minecraft_version
}

loom {
    mixin {
        defaultRefmapName = "${mod_id}.refmap.json"
    }
}

repositories {
    maven { url "https://maven.shedaniel.me/" }
    maven { url "https://maven.terraformersmc.com/" }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // do this for the time being, for some reason these builds arent on the maven
    implementation files("libs/cloth-config-26.1.154.jar")
    implementation files("libs/modmenu-18.0.0-alpha.8.jar")

    implementation include("com.maxmind.db:maxmind-db:3.2.0")
    implementation include("com.maxmind.geoip2:geoip2:4.3.1")

    // required because maxmind-db crashes without it
    implementation include("com.fasterxml.jackson.core:jackson-databind:2.19.2")
    implementation include("com.fasterxml.jackson.core:jackson-core:2.19.2")
    implementation include("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.19.2")
}

processResources {
    filteringCharset "UTF-8"

    inputs.property "version", mod_version
    inputs.property "minecraft_version", minecraft_version

    filesMatching("fabric.mod.json") {
        expand  "version": mod_version,
                "minecraft_version": minecraft_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
