# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
#org.gradle.parallel=true

minecraft_version=1.21
minecraft_version_group=1.21

mod_id=servercountryflags
mod_version=1.10.2

fabric_loader_version=0.15.11
fabric_version=0.100.1+1.21
fabric_minecraft_version_range=~1.21

# 1.20.1 version; 1.20.2 is not released
server_browser_artifact_id_forge=4739506
server_browser_artifact_id_fabric=4595354
# NeoForged version is not released, using Forge
server_browser_artifact_id_neoforged=4739506

forge_version=51.0.5
forge_version_range=[51,)
forge_loader_version_range=[51,)
forge_minecraft_version_range=[1.21,1.22)

neo_version=21.0.4-beta
neo_version_range=[21,)
neo_loader_version_range=[1,)

cloth_config_version=15.0.127
modmenu_version=11.0.0-beta.1
raknetify_version=1.21-0.1.0+alpha.5.123